export const data = [
  {
    id: 1,
    first_name: "Gabbie",
    last_name: "Brennans",
    email: "gbrennans0@nymag.com",
    gender: "Male",
    phone: "391-615-1334",
    address: "0587 Fulton Court",
    date_of_birth: "5/18/2022",
  },
  {
    id: 2,
    first_name: "Salomon",
    last_name: "Lechmere",
    email: "slechmere1@woothemes.com",
    gender: "Male",
    phone: "103-417-4858",
    address: "94538 Bluejay Park",
    date_of_birth: "4/10/2022",
  },
  {
    id: 3,
    first_name: "Olivier",
    last_name: "Shackle",
    email: "oshackle2@google.nl",
    gender: "Male",
    phone: "384-128-2146",
    address: "43913 Morningstar Pass",
    date_of_birth: "9/4/2022",
  },
  {
    id: 4,
    first_name: "Darcee",
    last_name: "Kidstone",
    email: "dkidstone3@kickstarter.com",
    gender: "Bigender",
    phone: "475-902-0952",
    address: "2645 Gale Center",
    date_of_birth: "4/3/2022",
  },
  {
    id: 5,
    first_name: "Vachel",
    last_name: "Dunkirk",
    email: "vdunkirk4@admin.ch",
    gender: "Male",
    phone: "143-559-3190",
    address: "7 Golden Leaf Road",
    date_of_birth: "10/17/2022",
  },
  {
    id: 6,
    first_name: "Willie",
    last_name: "Cottham",
    email: "wcottham5@accuweather.com",
    gender: "Male",
    phone: "321-447-1620",
    address: "9 Vernon Lane",
    date_of_birth: "10/23/2022",
  },
  {
    id: 7,
    first_name: "Rog",
    last_name: "Degnen",
    email: "rdegnen6@skype.com",
    gender: "Male",
    phone: "792-270-7463",
    address: "90865 Spenser Crossing",
    date_of_birth: "9/3/2022",
  },
  {
    id: 8,
    first_name: "Monti",
    last_name: "Stump",
    email: "mstump7@geocities.com",
    gender: "Male",
    phone: "317-998-8143",
    address: "47218 Warbler Way",
    date_of_birth: "11/12/2022",
  },
  {
    id: 9,
    first_name: "Yank",
    last_name: "Print",
    email: "yprint8@biblegateway.com",
    gender: "Male",
    phone: "129-237-8268",
    address: "97576 Chive Road",
    date_of_birth: "7/24/2022",
  },
  {
    id: 10,
    first_name: "Sidonia",
    last_name: "Leguay",
    email: "sleguay9@usatoday.com",
    gender: "Female",
    phone: "363-962-0611",
    address: "90745 Erie Crossing",
    date_of_birth: "5/15/2022",
  },
  {
    id: 11,
    first_name: "Sherie",
    last_name: "Cyson",
    email: "scysona@cdc.gov",
    gender: "Female",
    phone: "389-515-8698",
    address: "356 Sugar Park",
    date_of_birth: "9/26/2022",
  },
  {
    id: 12,
    first_name: "Austen",
    last_name: "Myring",
    email: "amyringb@weebly.com",
    gender: "Male",
    phone: "495-352-7573",
    address: "152 Fairview Terrace",
    date_of_birth: "2/1/2022",
  },
  {
    id: 13,
    first_name: "Minor",
    last_name: "Fido",
    email: "mfidoc@samsung.com",
    gender: "Male",
    phone: "496-262-6617",
    address: "6266 Fremont Junction",
    date_of_birth: "6/14/2022",
  },
  {
    id: 14,
    first_name: "Grove",
    last_name: "Youngs",
    email: "gyoungsd@ox.ac.uk",
    gender: "Genderfluid",
    phone: "278-792-6157",
    address: "28 Everett Alley",
    date_of_birth: "6/22/2022",
  },
  {
    id: 15,
    first_name: "Wesley",
    last_name: "Nafzger",
    email: "wnafzgere@ucoz.ru",
    gender: "Male",
    phone: "704-535-8561",
    address: "6 Farmco Court",
    date_of_birth: "4/12/2022",
  },
  {
    id: 16,
    first_name: "Aimee",
    last_name: "Drennan",
    email: "adrennanf@hao123.com",
    gender: "Female",
    phone: "107-702-1199",
    address: "343 Barby Way",
    date_of_birth: "10/15/2022",
  },
  {
    id: 17,
    first_name: "Randy",
    last_name: "Svanini",
    email: "rsvaninig@cnet.com",
    gender: "Polygender",
    phone: "790-738-5658",
    address: "35 Morrow Lane",
    date_of_birth: "3/13/2022",
  },
  {
    id: 18,
    first_name: "Viki",
    last_name: "Goseling",
    email: "vgoselingh@whitehouse.gov",
    gender: "Female",
    phone: "202-665-8855",
    address: "0 Johnson Point",
    date_of_birth: "4/9/2022",
  },
  {
    id: 19,
    first_name: "Flor",
    last_name: "Orrett",
    email: "forretti@imgur.com",
    gender: "Female",
    phone: "429-547-9222",
    address: "39687 Westridge Lane",
    date_of_birth: "8/13/2022",
  },
  {
    id: 20,
    first_name: "Del",
    last_name: "Grand",
    email: "dgrandj@ucoz.ru",
    gender: "Female",
    phone: "560-794-6651",
    address: "50680 Lien Court",
    date_of_birth: "9/27/2022",
  },
  {
    id: 21,
    first_name: "Cammy",
    last_name: "Simonato",
    email: "csimonatok@domainmarket.com",
    gender: "Non-binary",
    phone: "261-464-8611",
    address: "7 Surrey Road",
    date_of_birth: "4/13/2022",
  },
  {
    id: 22,
    first_name: "Lishe",
    last_name: "Spear",
    email: "lspearl@topsy.com",
    gender: "Female",
    phone: "302-797-1863",
    address: "3125 East Alley",
    date_of_birth: "1/19/2022",
  },
  {
    id: 23,
    first_name: "Elmo",
    last_name: "Domaschke",
    email: "edomaschkem@typepad.com",
    gender: "Male",
    phone: "535-843-7048",
    address: "2643 Westerfield Junction",
    date_of_birth: "11/14/2022",
  },
  {
    id: 24,
    first_name: "Darlleen",
    last_name: "Yeldon",
    email: "dyeldonn@marketwatch.com",
    gender: "Female",
    phone: "913-175-0808",
    address: "0 Sachs Alley",
    date_of_birth: "10/1/2022",
  },
  {
    id: 25,
    first_name: "Renato",
    last_name: "Lilleman",
    email: "rlillemano@desdev.cn",
    gender: "Male",
    phone: "477-514-9416",
    address: "1458 Donald Center",
    date_of_birth: "9/24/2022",
  },
];

export const columnData = [
  { id: 1, field: "id", header: "ID" },
  { id: 2, field: "first_name", header: "First Name" },
  { id: 3, field: "last_name", header: "Last Name" },
  { id: 4, field: "email", header: "Email" },
  { id: 5, field: "gender", header: "Gender" },
  { id: 6, field: "address", header: "Address" },
  { id: 7, field: "phone", header: "Phone No" },
  { id: 9, field: "date_of_birth", header: "DOB" },
  { id: 10, field: "delete", header: "Action" },
];
